"""empty message

Revision ID: 6_add_time_stamps
Revises: 5_dislike_model
Create Date: 2023-01-13 12:56:49.366439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6_add_time_stamps'
down_revision = '5_dislike_model'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dislikes', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('likes', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('photos', sa.Column('uploaded_at', sa.DateTime(), nullable=True))
    op.add_column('posts', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('posts', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('posts', 'likes',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('posts', 'dislikes',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'dislikes',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('posts', 'likes',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('posts', 'updated_at')
    op.drop_column('posts', 'created_at')
    op.drop_column('photos', 'uploaded_at')
    op.drop_column('likes', 'created_at')
    op.drop_column('dislikes', 'created_at')
    # ### end Alembic commands ###
